name: Build and Test Next.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Log MongoDB URI
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          node -e "
            const mongodburi = process.env.MONGODB_URI;
            console.log(mongodburi);
          "
      - name: Run build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: npm run build
