name: Build and Test Next.js App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Run build
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        run: |
          npm run build
          # Use the MONGODB_URI secret in your code
          node -e "console.log(process.env.MONGODB_URI)"