name: Build and Deploy to Docker Hub
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}

    - name: Build and Push Docker image
      run: |
        docker build \
          --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
          --build-arg RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
          --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
          --build-arg GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
          --build-arg NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
          --build-arg SENDER=${{ secrets.SENDER }} \
          --build-arg GMAIL_SECRET=${{ secrets.GMAIL_SECRET }} \
          -t bhaveshaswani112/anonymous-review .

        docker push bhaveshaswani112/anonymous-review:latest

    - name: Verify Pushed Image
      run: docker pull bhaveshaswani112/anonymous-review:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull bhaveshaswani112/anonymous-review:latest
          sudo docker stop anonymous-review || true
          sudo docker rm anonymous-review || true
          sudo docker run -d \
            --name anonymous-review \
            -p 3005:3000 \
            -e MONGODB_URI=${{ secrets.MONGODB_URI }} \
            -e RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
            -e NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            -e GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
            -e NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
            -e SENDER=${{ secrets.SENDER }} \
            -e GMAIL_SECRET=${{ secrets.GMAIL_SECRET }} \
            bhaveshaswani112/anonymous-review:latest
