name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: bhaveshaswani112/anonymous-review:latest
        build-args:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}

    - name: Verify Pushed Image
      run: docker pull bhaveshaswani112/anonymous-review:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          sudo docker pull bhaveshaswani112/anonymous-review:latest
          sudo docker stop web-app || true
          sudo docker rm web-app || true
          sudo docker run -d --name anonymous-review  -p 3005:3000 -e MONGODB_URI=${{ secrets.MONGODB_URI }} bhaveshaswani112/anonymous-review:latest
